---
- hosts: all
  become: yes
  gather_facts: no
  
  tasks:

     - name: disable selinux
       shell: "setenforce 0"

     - name: stop firewalld
       service:
         name: firewalld
         state: stopped
         enabled: no

     - name: install nfs pkg
       yum:
         name: nfs-utils
         state: present 
